import Head from 'next/head';
import styles from '../styles/Test.module.css';
import type { GetServerSideProps, NextPage } from 'next';
import sha256 from 'crypto-js/sha256';
import CryptoJS from 'crypto-js';
import { useRouter } from 'next/router';
import { useState } from 'react';
import LoginForm from '@/components/forms/LoginForm';
import RegisterForm from '@/components/forms/RegisterForm';
import getGoogleOAuthUrl from '../lib/client/getGoogleUrl';
import getFacebookUrl from '../lib/client/getFacebookUrl';

const Login: NextPage<{ code_challenge: string }> = ({ code_challenge }) => {
  const router = useRouter();
  const [serverError, setServerError] = useState<string | null>(null); // can pass setServerError as prop to both form components
  const [isLoginView, setIsLoginView] = useState<boolean>(true);

  return (
    <div>
      <Head>
        <title>RemindMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className={`bg-blueGrey-400 w-full h-screen ${styles.wrapper} items-center overflow-auto`}
        >
          <div className="col-start-4 col-end-10 row-span-1 row-end-3  flex justify-center  w-full h-full ">
            <div
              id="left"
              className="w-full flex flex-col p-3 h-full justify-between"
            >
              <div className=" h-full flex flex-col justify-center pl-7">
                <div className="font-semibold text-5xl">RemindMe</div>
                <div className="text-blueGrey-200 mt-3">
                  Did you forget something?
                </div>
              </div>
              <div className=" h-full pl-7 font-medium text-lg mt-5">
                Say goodbye to belated birthday wishes and missed dentist
                appointments
              </div>
              <div className=" h-full pl-7 font-medium text-lg">
                Use RemindMe to forget about forgetting
              </div>
            </div>
            <div
              id="right"
              className="w-full bg-blueGrey-800 border rounded-3xl p-5 m-3"
            >
              <div className="wrapper p-6 h-full flex flex-col">
                <div id="serverError">
                  {serverError && (
                    <p className="error mt-5 mb-5 text-red-500">
                      {serverError}
                    </p>
                  )}
                </div>
                <div id="formRender" className="mt-5">
                  {isLoginView ? (
                    <LoginForm
                      router={router}
                      setServerError={setServerError}
                    />
                  ) : (
                    <RegisterForm
                      setServerError={setServerError}
                      setIsLoginView={setIsLoginView}
                    />
                  )}
                </div>
                <div
                  id="OAuthLogin"
                  className="bg-blueGrey-300 mt-3 flex flex-col rounded-2xl"
                >
                  {' '}
                  <div className="flex self-center">
                    <div>-----</div>
                    <div>Or Login with</div>
                    <div>-----</div>
                  </div>
                  <div id="buttons">
                    <button onClick={() => router.push(getGoogleOAuthUrl())}>
                      Google
                    </button>
                    <button
                      className=""
                      onClick={() =>
                        router.push(getFacebookUrl(code_challenge))
                      }
                    >
                      Facebook
                    </button>
                  </div>
                </div>
                <div
                  id="footerText"
                  className="bg-blueGrey-300 mt-3 rounded-2xl"
                >
                  {isLoginView
                    ? 'Dont have an account? '
                    : 'Already Registered? '}
                  <span
                    className="hover:cursor-pointer"
                    onClick={() => setIsLoginView(!isLoginView)}
                  >
                    {isLoginView ? 'Sign up now ' : 'Login here '}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Login;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const code_verifier = process.env.CODE_VERIFIER as string;
  const hash = sha256(code_verifier);
  const code_challenge = CryptoJS.enc.Base64url.stringify(hash);
  return {
    props: {
      code_challenge: code_challenge,
    },
  };
};
