import Head from 'next/head';

export default function Test() {
  return (
    <div>
      <Head>
        <title>Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex w-full h-screen">
          <div className="bg-red-500 w-full  max-w-[400px]">left</div>
          <div className="bg-blue-500 w-full flex justify-between">
            <div>left</div>
            <div>right</div>
          </div>
        </div>
      </main>
    </div>
  );
}
